Repository googleapis/gax-ruby, pull requests merged in 2019-05, with the labels that each got.

#185 Remove OperationsClient
  .rubocop.yml
  lib/google/gax/operation.rb
  lib/google/longrunning/operations_client.rb
Labels: 2.0, cla: yes

#186 Remove BackoffSettings
  lib/google/gax/settings.rb
Labels: 2.0, cla: yes

#183 2.0/update errors
  .rubocop.yml
  lib/google/gax/api_call.rb
  lib/google/gax/errors.rb
  lib/google/gax/grpc.rb
  lib/google/gax/grpc/status_details.rb
  test/google/gax/error_test.rb
  test/google/gax/gax_error/status_details_test.rb
Labels: 2.0, :rotating_light:, cla: yes

#190 Add PagedEnumerable format_resource proc
  lib/google/gax/paged_enumerable.rb
  test/google/gax/paged_enumerable/format_resource_test.rb
Labels: 2.0, cla: yes

#189 Operation Updates
  Rakefile
  google-gax.gemspec
  lib/google/gax/operation.rb
  lib/google/gax/paged_enumerable.rb
  test/google/gax/operation_test.rb
Labels: 2.0, cla: yes, do not merge

#192 Update copyright attribution
  LICENSE
  lib/google/gax.rb
  lib/google/gax/api_call.rb
  lib/google/gax/api_call/options.rb
  lib/google/gax/api_call/retry_policy.rb
  lib/google/gax/errors.rb
  lib/google/gax/grpc.rb
  lib/google/gax/grpc/status_details.rb
  lib/google/gax/grpc/stub.rb
  lib/google/gax/operation.rb
  lib/google/gax/operation/retry_policy.rb
  lib/google/gax/paged_enumerable.rb
  lib/google/gax/protobuf.rb
  lib/google/gax/stream_input.rb
  lib/google/gax/version.rb
  test/fixtures/fixture.proto
  test/google/gax/api_call/call_test.rb
  test/google/gax/api_call/options_test.rb
  test/google/gax/api_call/raise_test.rb
  test/google/gax/api_call/retry/raise_test.rb
  test/google/gax/api_call/retry/retry_test.rb
  test/google/gax/api_call/retry_policy/call_test.rb
  test/google/gax/api_call/retry_policy/settings_test.rb
  test/google/gax/error_test.rb
  test/google/gax/gax_error/status_details_test.rb
  test/google/gax/grpc/stub_test.rb
  test/google/gax/operation_test.rb
  test/google/gax/paged_enumerable/enum_test.rb
  test/google/gax/paged_enumerable/format_resource_test.rb
  test/google/gax/paged_enumerable/invalid_request_test.rb
  test/google/gax/paged_enumerable/invalid_response_test.rb
  test/google/gax/paged_enumerable/valid_request_response_test.rb
  test/google/gax/protobuf/coerce_test.rb
  test/google/gax/protobuf/time_test.rb
  test/google/gax/stream_input_test.rb
Labels: 2.0, cla: yes

#193 Update copyright attribution
  LICENSE
  lib/google/gax.rb
  lib/google/gax/api_callable.rb
  lib/google/gax/bundling.rb
  lib/google/gax/constants.rb
  lib/google/gax/errors.rb
  lib/google/gax/grpc.rb
  lib/google/gax/operation.rb
  lib/google/gax/path_template.rb
  lib/google/gax/settings.rb
  lib/google/gax/util.rb
  lib/google/gax/version.rb
  spec/fixtures/fixture.proto
  spec/google/gax/api_callable_spec.rb
  spec/google/gax/bundling_spec.rb
  spec/google/gax/error_spec.rb
  spec/google/gax/grpc_spec.rb
  spec/google/gax/operation_spec.rb
  spec/google/gax/path_template_spec.rb
  spec/google/gax/settings_spec.rb
  spec/google/gax/util_spec.rb
Labels: cla: yes, type: cleanup

#191 Update dependencies for 2.0
  google-gax.gemspec
Labels: 2.0, cla: yes

#194 Add Configuration
  .rubocop.yml
  lib/google/gax.rb
  lib/google/gax/configuration.rb
  test/google/gax/configuration_test.rb
Labels: 2.0, cla: yes

#197 Defer runtime dependency on gRPC
  lib/google/gax/errors.rb
Labels: 2.0, cla: yes

#195 Add DerivedConfiguration
  .rubocop.yml
  lib/google/gax/configuration.rb
  lib/google/gax/configuration/deferred_value.rb
  lib/google/gax/configuration/derived.rb
  lib/google/gax/configuration/schema.rb
  test/google/gax/configuration/derive_test.rb
  test/google/gax/configuration_test.rb
Labels: 2.0, :rotating_light:, cla: yes

#196 Add Config DSL
  .rubocop.yml
  lib/google/gax/config.rb
  lib/google/gax/config/method.rb
  test/google/gax/config/attrs_test.rb
  test/google/gax/config/errors_test.rb
  test/google/gax/config/method_test.rb
  test/google/gax/config/nested_test.rb
Labels: 2.0, cla: yes

#201 Add channel_args to GRPC::Stub.new
  lib/google/gax/grpc/stub.rb
Labels: 2.0, cla: yes

#202 Allow Signet::OAuth2::Client as credential arg
  .rubocop.yml
  lib/google/gax/grpc/stub.rb
Labels: 2.0, cla: yes

#204 Ensure metadata is merged properly
  lib/google/gax/settings.rb
  spec/google/gax/call_settings_spec.rb
Labels: cla: yes, type: bug

#205 Add OperationsClient metadata argument
  lib/google/gax/settings.rb
  lib/google/longrunning/operations_client.rb
Labels: cla: yes

#207 Fix yields for non-retryable op
  CHANGELOG.md
  lib/google/gax/api_callable.rb
  lib/google/gax/version.rb
Labels: cla: yes

#208 Call GAPIC client using positional args
  lib/google/gax/operation.rb
Labels: 2.0, cla: yes

#206 Refactor Gax::GRPC::Stub to a class
  lib/google/gax/grpc/stub.rb
  lib/google/gax/paged_enumerable.rb
Labels: cla: yes

#209 Add tests for recent changes
  test/google/gax/config/errors_test.rb
  test/google/gax/grpc/stub_test.rb
  test/google/gax/operation_test.rb
  test/google/gax/paged_enumerable/enum_test.rb
  test/google/gax/paged_enumerable/format_resource_test.rb
  test/google/gax/paged_enumerable/invalid_request_test.rb
  test/google/gax/paged_enumerable/invalid_response_test.rb
  test/google/gax/paged_enumerable/valid_request_response_test.rb
Labels: cla: yes

#211 Fix deadline calculation when timeout is nil
  lib/google/gax/api_callable.rb
Labels: cla: yes, type: bug
